<?php

namespace Database\Seeders;

use App\Models\Theme;
use Illuminate\Database\Seeder;

class ThemeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $colors = [
            // System Themes
            [
                'name' => 'Default',
                'colors' => [
                    'root' => [
                        'background' => '0 0% 100%',
                        'foreground' => '240 10% 4%',
                        'muted' => '240 5% 96%',
                        'mutedForeground' => '240 4% 46%',
                        'popover' => '240 4% 46%',
                        'popoverForeground' => '240 10% 4%',
                        'card' => '0 0% 100%',
                        'cardForeground' => '240 10% 4%',
                        'border' => '240 6% 90%',
                        'input' => '240 6% 90%',
                        'primary' => '240 6% 10%',
                        'primaryForeground' => '0 0% 98%',
                        'secondary' => '240 5% 96%',
                        'secondaryForeground' => '0 6% 10%',
                        'accent' => '240 5% 96%',
                        'accentForeground' => '240 6% 10%',
                        'destructive' => '0 84% 60%',
                        'destructiveForeground' => '0 0% 98%',
                        'ring' => '240 10% 4%',
                    ],
                ],
                'radius' => '0.5rem',
                'is_system' => true,
                'deriveFrom' => 'primary',
            ],
            [
                'name' => 'Cranberry',
                'colors' => [
                    'root' => [
                        'background' => '332 70% 99%',
                        'foreground' => '332 90% 8%',
                        'muted' => '332 60% 97%',
                        'mutedForeground' => '332 50% 15%',
                        'popover' => '332 100% 99%',
                        'popoverForeground' => '332 90% 8%',
                        'card' => '332 70% 99%',
                        'cardForeground' => '332 90% 8%',
                        'border' => '332 90% 95%',
                        'input' => '332 90% 95%',
                        'primary' => '332 76% 43%',
                        'primaryForeground' => '332 100% 99%',
                        'secondary' => '332 50% 96%',
                        'secondaryForeground' => '332 81% 26%',
                        'accent' => '148 25% 50%',
                        'accentForeground' => '148 50% 97%',
                        'destructive' => '349 75% 58%',
                        'destructiveForeground' => '349 80% 97%',
                        'ring' => '332 85% 80%',
                    ],
                ],
                'radius' => '0.5rem',
                'is_system' => true,
                'deriveFrom' => 'primary',
            ],
            [
                'name' => 'Rostro',
                'colors' => [
                    'root' => [
                        'background' => '212 100% 99%',
                        'foreground' => '212 90% 8%',
                        'muted' => '212 60% 97%',
                        'mutedForeground' => '212 50% 15%',
                        'popover' => '212 100% 99%',
                        'popoverForeground' => '212 90% 8%',
                        'card' => '212 100% 99%',
                        'cardForeground' => '212 90% 8%',
                        'border' => '212 66% 92%',
                        'input' => '212 66% 92%',
                        'primary' => '212 65% 40%',
                        'primaryForeground' => '212 100% 99%',
                        'secondary' => '212 50% 96%',
                        'secondaryForeground' => '212 40% 26%',
                        'accent' => '34 90% 52%',
                        'accentForeground' => '34 50% 96%',
                        'destructive' => '349 75% 58%',
                        'destructiveForeground' => '349 80% 97%',
                        'ring' => '212 85% 80%',
                    ],
                ],
                'radius' => '0.5rem',
                'is_system' => true,
                'deriveFrom' => 'primary',
            ],
            [
                'name' => 'Spruce',
                'colors' => [
                    'root' => [
                        'background' => '159 70% 99%',
                        'foreground' => '159 90% 8%',
                        'muted' => '159 60% 97%',
                        'mutedForeground' => '159 50% 15%',
                        'popover' => '159 100% 99%',
                        'popoverForeground' => '159 90% 8%',
                        'card' => '159 70% 99%',
                        'cardForeground' => '159 90% 8%',
                        'border' => '159 66% 92%',
                        'input' => '159 66% 92%',
                        'primary' => '159 90% 34%',
                        'primaryForeground' => '159 100% 99%',
                        'secondary' => '159 50% 96%',
                        'secondaryForeground' => '159 50% 25%',
                        'accent' => '292 37% 59%',
                        'accentForeground' => '292 70% 98%',
                        'destructive' => '349 75% 58%',
                        'destructiveForeground' => '349 80% 97%',
                        'ring' => '159 65% 80%',
                    ],
                ],
                'radius' => '0.5rem',
                'is_system' => true,
                'deriveFrom' => 'primary',
            ],
            [
                'name' => 'Honeybee',
                'colors' => [
                    'root' => [
                        'background' => '54 70% 99%',
                        'foreground' => '54 90% 8%',
                        'muted' => '54 60% 97%',
                        'mutedForeground' => '54 50% 15%',
                        'popover' => '54 100% 99%',
                        'popoverForeground' => '54 90% 8%',
                        'card' => '54 70% 99%',
                        'cardForeground' => '54 90% 8%',
                        'border' => '54 66% 92%',
                        'input' => '54 66% 92%',
                        'primary' => '54 65% 62%',
                        'primaryForeground' => '54 70% 10%',
                        'secondary' => '54 50% 96%',
                        'secondaryForeground' => '54 92% 38%',
                        'accent' => '0 88% 68%',
                        'accentForeground' => '0 50% 97%',
                        'destructive' => '349 75% 58%',
                        'destructiveForeground' => '349 80% 97%',
                        'ring' => '54 65% 80%',
                    ],
                ],
                'radius' => '0.5rem',
                'is_system' => true,
                'deriveFrom' => 'primary',
            ],
            [
                'name' => 'Strawbaerie',
                'colors' => [
                    'root' => [
                        'background' => '22 70% 99%',
                        'foreground' => '22 90% 8%',
                        'muted' => '22 60% 97%',
                        'mutedForeground' => '22 50% 15%',
                        'popover' => '22 100% 99%',
                        'popoverForeground' => '22 90% 8%',
                        'card' => '22 70% 99%',
                        'cardForeground' => '22 90% 8%',
                        'border' => '22 66% 92%',
                        'input' => '22 66% 92%',
                        'primary' => '22 87% 55%',
                        'primaryForeground' => '22 70% 99%',
                        'secondary' => '22 50% 96%',
                        'secondaryForeground' => '22 97% 38%',
                        'accent' => '94 50% 49%',
                        'accentForeground' => '94 50% 97%',
                        'destructive' => '349 75% 58%',
                        'destructiveForeground' => '349 80% 97%',
                        'ring' => '22 65% 80%',
                    ],
                ],
                'radius' => '0.5rem',
                'is_system' => true,
                'deriveFrom' => 'primary',
            ],
            // Company Themes
            [
                'name' => '4 State Trucks',
                'colors' => [
                    'root' => [
                        'background' => '56 100% 99%',
                        'foreground' => '56 90% 8%',
                        'muted' => '56 60% 97%',
                        'mutedForeground' => '56 50% 15%',
                        'popover' => '56 100% 99%',
                        'popoverForeground' => '56 90% 8%',
                        'card' => '56 100% 99%',
                        'cardForeground' => '56 90% 8%',
                        'border' => '56 66% 92%',
                        'input' => '56 66% 92%',
                        'primary' => '354 100% 45%',
                        'primaryForeground' => '354 50% 96%',
                        'secondary' => '56 50% 96%',
                        'secondaryForeground' => '56 40% 26%',
                        'accent' => '56 100% 50%',
                        'accentForeground' => '56 40% 26%',
                        'destructive' => '349 75% 58%',
                        'destructiveForeground' => '349 80% 97%',
                        'ring' => '56 85% 80%',
                    ],
                ],
                'radius' => '0.5rem',
                'is_system' => false,
                'deriveFrom' => 'accent',
            ],
            [
                'name' => 'Jayco',
                'colors' => [
                    'root' => [
                        'background' => '202 70% 99%',
                        'foreground' => '202 90% 8%',
                        'muted' => '202 60% 97%',
                        'mutedForeground' => '202 50% 15%',
                        'popover' => '202 100% 99%',
                        'popoverForeground' => '202 90% 8%',
                        'card' => '202 70% 99%',
                        'cardForeground' => '202 90% 8%',
                        'border' => '202 66% 92%',
                        'input' => '202 66% 92%',
                        'primary' => '202 100% 38%',
                        'primaryForeground' => '202 100% 99%',
                        'secondary' => '202 50% 96%',
                        'secondaryForeground' => '202 50% 25%',
                        'accent' => '12 22% 5%',
                        'accentForeground' => '0 0% 98%',
                        'destructive' => '349 75% 58%',
                        'destructiveForeground' => '349 80% 97%',
                        'ring' => '202 65% 80%',
                    ],
                ],
                'radius' => '0.5rem',
                'is_system' => false,
                'deriveFrom' => 'primary',
            ],
            [
                'name' => 'Loftwall',
                'colors' => [
                    'root' => [
                        'background' => '141 70% 99%',
                        'foreground' => '141 90% 8%',
                        'muted' => '141 60% 97%',
                        'mutedForeground' => '141 50% 15%',
                        'popover' => '141 100% 99%',
                        'popoverForeground' => '141 90% 8%',
                        'card' => '141 70% 99%',
                        'cardForeground' => '141 90% 8%',
                        'border' => '141 66% 92%',
                        'input' => '141 66% 92%',
                        'primary' => '141 93% 38%',
                        'primaryForeground' => '141 70% 10%',
                        'secondary' => '141 50% 96%',
                        'secondaryForeground' => '141 92% 38%',
                        'accent' => '39 100% 56%',
                        'accentForeground' => '39 50% 97%',
                        'destructive' => '349 75% 58%',
                        'destructiveForeground' => '349 80% 97%',
                        'ring' => '141 65% 80%',
                    ],
                ],
                'radius' => '0.5rem',
                'is_system' => false,
                'deriveFrom' => 'primary',
            ],
            [
                'name' => 'The Ubique Group',
                'colors' => [
                    'root' => [
                        'background' => '217 70% 99%',
                        'foreground' => '217 90% 8%',
                        'muted' => '217 60% 97%',
                        'mutedForeground' => '217 50% 15%',
                        'popover' => '217 100% 99%',
                        'popoverForeground' => '217 90% 8%',
                        'card' => '217 70% 99%',
                        'cardForeground' => '217 90% 8%',
                        'border' => '217 66% 92%',
                        'input' => '217 66% 92%',
                        'primary' => '217 59% 24%',
                        'primaryForeground' => '217 70% 99%',
                        'secondary' => '217 50% 96%',
                        'secondaryForeground' => '217 97% 38%',
                        'accent' => '23 64% 63%',
                        'accentForeground' => '23 50% 97%',
                        'destructive' => '349 75% 58%',
                        'destructiveForeground' => '349 80% 97%',
                        'ring' => '217 65% 80%',
                    ],
                ],
                'radius' => '0.5rem',
                'is_system' => false,
                'deriveFrom' => 'primary',
            ],
        ];

        foreach ($colors as $color) {
            Theme::create($color);
        }
    }
}
